### ISSUE TITLE
そういえば

### ISSUE THREAD

**Issue by yamanetoshi** [RHGReadingOkinawa/rhgreadingokinawa.github.com#15]
@higumachan 

ええと、完全に別件です。

まるさ君に聞いてるかもしれませんが、9 月頃に[Kernel/VM 探検隊](http://www.kernelvm.org/)の沖縄版を開催する予定になっております。競技プログラミングだったりあるいはそうじゃない部分でも構わないのですが、発信を検討頂ければ幸いです。

よろしくお願いします。

**Comment by higumachan** [comment]
その話はマルサから聞いているんですけど、僕がやってる分野って画像処理系であんまり低レイヤの部分を知らないので話すことが…みたいな感じですね〜。
一番、イベントにマッチする話題で語れそうなのがLISP処理系(構文解析と内部処理とGC)を実装した話ですかね〜

**Comment by yamanetoshi** [comment]
ぼくがくまの人を連想したのは競技プログラミングでした。。
でも LISP 処理系の話は十分マッチしてると思っています。

ご検討頂ければ幸いです。
主催な人曰く

> 敢えて一言でいうと「低レイヤーとかOS・VM・言語処理系とかの話を、聞いてる人のレベルに合わせて敷居を下げたりしないで、おもいきり話してよい場（むしろ出来るだけ聞いている人を置き去りにする事が推奨されている）」という感じ

とのことです。

如何ですか？

**Comment by higumachan** [comment]
じゃあ、LISP処理系を実装したときの話をしてみたいと思います！

競技プログラミングはあの時は県内１位だったのですが後輩にすごいやつが育ってもうそいつにはかなわないみたいな感じですね〜(もともと、僕はそんなに得意ではなかった的な

**Comment by yamanetoshi** [comment]
時間てどの程度必要? LT 程度なのかもっとがっつりなのか。

あと後輩の凄い人も発信してもらえるとアレです。

内地の人も三名くらい発信してくれるみたいなので内容的にも面白くなりそうです。開催は 9.21 午後で確定する方向です。

**Comment by higumachan** [comment]
たぶん10分くらいになるのではないかな〜と思います！

**Comment by yamanetoshi** [comment]
了解です。とは言え内地から三名いらっしゃるってことなので自分アピールなソレ含めてで内容厚くすること含めて検討頂けると幸いです。

この件、違うチャネルでまた連絡入れさせて頂きますね。
