### ISSUE TITLE
pull request を merge する時のルールについて

### ISSUE THREAD

**Issue by yamanetoshi** [RHGReadingOkinawa/rhgreadingokinawa.github.com#17]
ルールが設定されていないようなので検討して決める必要あり。

二名の `:+1:` ないし LGTM で merge しちゃって良いってルールでいいすか？

**Comment by hanachin** [comment]
OK :ok_hand: です

**Comment by yamanetoshi** [comment]
@higumachan が OK であればこのルールでアレします。確認願います。

**Comment by higumachan** [comment]
すいません、遅れましたOKです！

**Comment by yamanetoshi** [comment]
@higumachan 

とりあえず Pull Request のレビュして OK 分は merge お願い。

**Comment by yamanetoshi** [comment]
とりあえず二名ってことで close しますね。
