### ISSUE TITLE
参加形態になれる

### ISSUE THREAD

**Issue by higumachan** [RHGReadingOkinawa/rhgreadingokinawa.github.com#3]
RHGを読むわけじゃないけど。
参加のフローを通すことによって、参加形態になれるのを目的にします。

**Comment by higumachan** [comment]
感想
Githubを使ったリモート読書会のすすめかたについてわかったような気がします。

**Comment by yamanetoshi** [comment]
```
$ jekyll serve 
```

で確認すると文字化けてるんですよね。。何が悪いんだろ。
